from os import environ

# if you set a property in SESSION_CONFIG_DEFAULTS, it will be inherited by all configs
# in SESSION_CONFIGS, except those that explicitly override it.
# the session config can be accessed from methods in your apps as self.session.config,
# e.g. self.session.config['participation_fee']

SESSION_CONFIG_DEFAULTS = dict(
    real_world_currency_per_point = 1.00, 
    num_demo_participants = 4,
    SG_lengths = [2,3,1,4],
    SG_totalNum = len([2,3,1,4]),
    payoff_1 = [[48, 12],[50, 25]],
    payoff_2 = [[24, 12],[48, 20]],
    expPoints_Red = 33.75,
    expPoints_Blue = 26,
    participation_fee=5.00,
    quiz_fee = 0.25,
    avg_earn = 19,
    low_earn = 5,
    high_earn = 28,
    minExpTime = 50,
    maxExpTime = 60,
    time_welcome = 0.15,
    time_period = 2,
    time_intro = 15,
    time_next = 0.15,
    time_quiz = 5,
    num_ques = 8,
    contProb = 75,
    die_N = 8,
    doc = ""
)

SESSION_CONFIGS = [
    dict(
        name = 'mmc_rep_TSS',
        display_name = "MMC Prisoner Experiment TSS",
        app_sequence = ['mmc_rep_intro_TSS','mmc_rep_exp_TSS','mmc_rep_questionnaire'],
        USE_POINTS = True,
        exRate = 1250,
        real_world_currency_per_point = 1/1250,
        num_demo_participants = SESSION_CONFIG_DEFAULTS["num_demo_participants"],
        SG_lengths = SESSION_CONFIG_DEFAULTS["SG_lengths"],
        SG_totalNum = SESSION_CONFIG_DEFAULTS["SG_totalNum"],
        payoff_1 = SESSION_CONFIG_DEFAULTS["payoff_1"],
        payoff_2 = SESSION_CONFIG_DEFAULTS["payoff_2"],
        expPoints_Red = SESSION_CONFIG_DEFAULTS["expPoints_Red"],
        expPoints_Blue = SESSION_CONFIG_DEFAULTS["expPoints_Blue"],
        participation_fee = SESSION_CONFIG_DEFAULTS["participation_fee"],
        quiz_fee = SESSION_CONFIG_DEFAULTS["quiz_fee"],
        avg_earn = SESSION_CONFIG_DEFAULTS["avg_earn"],
        low_earn = SESSION_CONFIG_DEFAULTS["low_earn"],
        high_earn = SESSION_CONFIG_DEFAULTS["high_earn"],
        minExpTime = SESSION_CONFIG_DEFAULTS["minExpTime"],
        maxExpTime = SESSION_CONFIG_DEFAULTS["maxExpTime"],
        time_welcome = SESSION_CONFIG_DEFAULTS["time_welcome"],
        time_period = SESSION_CONFIG_DEFAULTS["time_period"],
        time_intro = SESSION_CONFIG_DEFAULTS["time_intro"],
        time_next = SESSION_CONFIG_DEFAULTS["time_next"],
        time_quiz = SESSION_CONFIG_DEFAULTS["time_quiz"],
        num_ques = SESSION_CONFIG_DEFAULTS["num_ques"],
        contProb = SESSION_CONFIG_DEFAULTS["contProb"],
        die_N = SESSION_CONFIG_DEFAULTS["die_N"],
    ),
    dict(
        name = 'mmc_rep_TSS_Lab',
        display_name = "MMC Prisoner Experiment TSS Lab",
        app_sequence = ['mmc_rep_intro_off_TSS','mmc_rep_exp_off_TSS','mmc_rep_questionnaire'],
        USE_POINTS = True,
        exRate = 1250,
        real_world_currency_per_point = 1/1250,
        num_demo_participants = SESSION_CONFIG_DEFAULTS["num_demo_participants"],
        SG_lengths = SESSION_CONFIG_DEFAULTS["SG_lengths"],
        SG_totalNum = SESSION_CONFIG_DEFAULTS["SG_totalNum"],
        payoff_1 = SESSION_CONFIG_DEFAULTS["payoff_1"],
        payoff_2 = SESSION_CONFIG_DEFAULTS["payoff_2"],
        expPoints_Red = SESSION_CONFIG_DEFAULTS["expPoints_Red"],
        expPoints_Blue = SESSION_CONFIG_DEFAULTS["expPoints_Blue"],
        participation_fee = SESSION_CONFIG_DEFAULTS["participation_fee"],
        quiz_fee = SESSION_CONFIG_DEFAULTS["quiz_fee"],
        avg_earn = SESSION_CONFIG_DEFAULTS["avg_earn"],
        low_earn = SESSION_CONFIG_DEFAULTS["low_earn"],
        high_earn = SESSION_CONFIG_DEFAULTS["high_earn"],
        minExpTime = SESSION_CONFIG_DEFAULTS["minExpTime"],
        maxExpTime = SESSION_CONFIG_DEFAULTS["maxExpTime"],
        time_welcome = SESSION_CONFIG_DEFAULTS["time_welcome"],
        time_period = SESSION_CONFIG_DEFAULTS["time_period"],
        time_intro = SESSION_CONFIG_DEFAULTS["time_intro"],
        time_next = SESSION_CONFIG_DEFAULTS["time_next"],
        time_quiz = SESSION_CONFIG_DEFAULTS["time_quiz"],
        num_ques = SESSION_CONFIG_DEFAULTS["num_ques"],
        contProb = SESSION_CONFIG_DEFAULTS["contProb"],
        die_N = SESSION_CONFIG_DEFAULTS["die_N"],
    ),
    dict(
        name = 'mmc_rep_TSM',
        display_name = "MMC Prisoner Experiment TSM",
        app_sequence = ['mmc_rep_intro_TSM','mmc_rep_exp_TSM','mmc_rep_questionnaire'],
        USE_POINTS = True,
        exRate = 1250,
        real_world_currency_per_point = 1/1250,
        num_demo_participants = SESSION_CONFIG_DEFAULTS["num_demo_participants"],
        SG_lengths = SESSION_CONFIG_DEFAULTS["SG_lengths"],
        SG_totalNum = SESSION_CONFIG_DEFAULTS["SG_totalNum"],
        payoff_1 = SESSION_CONFIG_DEFAULTS["payoff_1"],
        payoff_2 = SESSION_CONFIG_DEFAULTS["payoff_2"],
        expPoints_Red = SESSION_CONFIG_DEFAULTS["expPoints_Red"],
        expPoints_Blue = SESSION_CONFIG_DEFAULTS["expPoints_Blue"],
        participation_fee = SESSION_CONFIG_DEFAULTS["participation_fee"],
        quiz_fee = SESSION_CONFIG_DEFAULTS["quiz_fee"],
        avg_earn = SESSION_CONFIG_DEFAULTS["avg_earn"],
        low_earn = SESSION_CONFIG_DEFAULTS["low_earn"],
        high_earn = SESSION_CONFIG_DEFAULTS["high_earn"],
        minExpTime = SESSION_CONFIG_DEFAULTS["minExpTime"],
        maxExpTime = SESSION_CONFIG_DEFAULTS["maxExpTime"],
        time_welcome = SESSION_CONFIG_DEFAULTS["time_welcome"],
        time_period = SESSION_CONFIG_DEFAULTS["time_period"],
        time_intro = SESSION_CONFIG_DEFAULTS["time_intro"],
        time_next = SESSION_CONFIG_DEFAULTS["time_next"],
        time_quiz = SESSION_CONFIG_DEFAULTS["time_quiz"],
        num_ques = SESSION_CONFIG_DEFAULTS["num_ques"],
        contProb = SESSION_CONFIG_DEFAULTS["contProb"],
        die_N = SESSION_CONFIG_DEFAULTS["die_N"],
    ),
    dict(
        name = 'mmc_rep_TSM_Lab',
        display_name = "MMC Prisoner Experiment TSM Lab",
        app_sequence  = ['mmc_rep_intro_off_TSM','mmc_rep_exp_off_TSM','mmc_rep_questionnaire'],
        USE_POINTS = True,
        exRate = 1250,
        real_world_currency_per_point = 1/1250,
        num_demo_participants = SESSION_CONFIG_DEFAULTS["num_demo_participants"],
        SG_lengths = SESSION_CONFIG_DEFAULTS["SG_lengths"],
        SG_totalNum = SESSION_CONFIG_DEFAULTS["SG_totalNum"],
        payoff_1 = SESSION_CONFIG_DEFAULTS["payoff_1"],
        payoff_2 = SESSION_CONFIG_DEFAULTS["payoff_2"],
        expPoints_Red = SESSION_CONFIG_DEFAULTS["expPoints_Red"],
        expPoints_Blue = SESSION_CONFIG_DEFAULTS["expPoints_Blue"],
        participation_fee = SESSION_CONFIG_DEFAULTS["participation_fee"],
        quiz_fee = SESSION_CONFIG_DEFAULTS["quiz_fee"],
        avg_earn = SESSION_CONFIG_DEFAULTS["avg_earn"],
        low_earn = SESSION_CONFIG_DEFAULTS["low_earn"],
        high_earn = SESSION_CONFIG_DEFAULTS["high_earn"],
        minExpTime = SESSION_CONFIG_DEFAULTS["minExpTime"],
        maxExpTime = SESSION_CONFIG_DEFAULTS["maxExpTime"],
        time_welcome = SESSION_CONFIG_DEFAULTS["time_welcome"],
        time_period = SESSION_CONFIG_DEFAULTS["time_period"],
        time_intro = SESSION_CONFIG_DEFAULTS["time_intro"],
        time_next = SESSION_CONFIG_DEFAULTS["time_next"],
        time_quiz = SESSION_CONFIG_DEFAULTS["time_quiz"],
        num_ques = SESSION_CONFIG_DEFAULTS["num_ques"],
        contProb = SESSION_CONFIG_DEFAULTS["contProb"],
        die_N = SESSION_CONFIG_DEFAULTS["die_N"],
    ),
    dict(
        name='mmc_rep_TAS',
        display_name="MMC Prisoner Experiment TAS",
        app_sequence=['mmc_rep_intro_TAS','mmc_rep_exp_TAS','mmc_rep_questionnaire'],
        USE_POINTS = True,
        exRate = 1250,
        real_world_currency_per_point = 1/1250,
        num_demo_participants = SESSION_CONFIG_DEFAULTS["num_demo_participants"],
        SG_lengths = SESSION_CONFIG_DEFAULTS["SG_lengths"],
        SG_totalNum = SESSION_CONFIG_DEFAULTS["SG_totalNum"],
        payoff_1 = SESSION_CONFIG_DEFAULTS["payoff_1"],
        payoff_2 = SESSION_CONFIG_DEFAULTS["payoff_2"],
        expPoints_Red = SESSION_CONFIG_DEFAULTS["expPoints_Red"],
        expPoints_Blue = SESSION_CONFIG_DEFAULTS["expPoints_Blue"],
        participation_fee = SESSION_CONFIG_DEFAULTS["participation_fee"],
        quiz_fee = SESSION_CONFIG_DEFAULTS["quiz_fee"],
        avg_earn = SESSION_CONFIG_DEFAULTS["avg_earn"],
        low_earn = SESSION_CONFIG_DEFAULTS["low_earn"],
        high_earn = SESSION_CONFIG_DEFAULTS["high_earn"],
        minExpTime = SESSION_CONFIG_DEFAULTS["minExpTime"],
        maxExpTime = SESSION_CONFIG_DEFAULTS["maxExpTime"],
        time_welcome = SESSION_CONFIG_DEFAULTS["time_welcome"],
        time_period = SESSION_CONFIG_DEFAULTS["time_period"],
        time_intro = SESSION_CONFIG_DEFAULTS["time_intro"],
        time_next = SESSION_CONFIG_DEFAULTS["time_next"],
        time_quiz = SESSION_CONFIG_DEFAULTS["time_quiz"],
        num_ques = SESSION_CONFIG_DEFAULTS["num_ques"],
        contProb = SESSION_CONFIG_DEFAULTS["contProb"],
        die_N = SESSION_CONFIG_DEFAULTS["die_N"],
    ),
    dict(
        name='mmc_rep_TAS_Lab',
        display_name="MMC Prisoner Experiment TAS Lab",
        app_sequence=['mmc_rep_intro_off_TAS','mmc_rep_exp_off_TAS','mmc_rep_questionnaire'],
        USE_POINTS = True,
        exRate = 1250,
        real_world_currency_per_point = 1/1250,
        num_demo_participants = SESSION_CONFIG_DEFAULTS["num_demo_participants"],
        SG_lengths = SESSION_CONFIG_DEFAULTS["SG_lengths"],
        SG_totalNum = SESSION_CONFIG_DEFAULTS["SG_totalNum"],
        payoff_1 = SESSION_CONFIG_DEFAULTS["payoff_1"],
        payoff_2 = SESSION_CONFIG_DEFAULTS["payoff_2"],
        expPoints_Red = SESSION_CONFIG_DEFAULTS["expPoints_Red"],
        expPoints_Blue = SESSION_CONFIG_DEFAULTS["expPoints_Blue"],
        participation_fee = SESSION_CONFIG_DEFAULTS["participation_fee"],
        quiz_fee = SESSION_CONFIG_DEFAULTS["quiz_fee"],
        avg_earn = SESSION_CONFIG_DEFAULTS["avg_earn"],
        low_earn = SESSION_CONFIG_DEFAULTS["low_earn"],
        high_earn = SESSION_CONFIG_DEFAULTS["high_earn"],
        minExpTime = SESSION_CONFIG_DEFAULTS["minExpTime"],
        maxExpTime = SESSION_CONFIG_DEFAULTS["maxExpTime"],
        time_welcome = SESSION_CONFIG_DEFAULTS["time_welcome"],
        time_period = SESSION_CONFIG_DEFAULTS["time_period"],
        time_intro = SESSION_CONFIG_DEFAULTS["time_intro"],
        time_next = SESSION_CONFIG_DEFAULTS["time_next"],
        time_quiz = SESSION_CONFIG_DEFAULTS["time_quiz"],
        num_ques = SESSION_CONFIG_DEFAULTS["num_ques"],
        contProb = SESSION_CONFIG_DEFAULTS["contProb"],
        die_N = SESSION_CONFIG_DEFAULTS["die_N"],
    ),
    dict(
        name='mmc_rep_TAM',
        display_name="MMC Prisoner Experiment TAM",
        app_sequence=['mmc_rep_intro_TAM','mmc_rep_exp_TAM','mmc_rep_questionnaire'],
        USE_POINTS = True,
        exRate = 1250,
        real_world_currency_per_point = 1/1250,
        num_demo_participants = SESSION_CONFIG_DEFAULTS["num_demo_participants"],
        SG_lengths = SESSION_CONFIG_DEFAULTS["SG_lengths"],
        SG_totalNum = SESSION_CONFIG_DEFAULTS["SG_totalNum"],
        payoff_1 = SESSION_CONFIG_DEFAULTS["payoff_1"],
        payoff_2 = SESSION_CONFIG_DEFAULTS["payoff_2"],
        expPoints_Red = SESSION_CONFIG_DEFAULTS["expPoints_Red"],
        expPoints_Blue = SESSION_CONFIG_DEFAULTS["expPoints_Blue"],
        participation_fee = SESSION_CONFIG_DEFAULTS["participation_fee"],
        quiz_fee = SESSION_CONFIG_DEFAULTS["quiz_fee"],
        avg_earn = SESSION_CONFIG_DEFAULTS["avg_earn"],
        low_earn = SESSION_CONFIG_DEFAULTS["low_earn"],
        high_earn = SESSION_CONFIG_DEFAULTS["high_earn"],
        minExpTime = SESSION_CONFIG_DEFAULTS["minExpTime"],
        maxExpTime = SESSION_CONFIG_DEFAULTS["maxExpTime"],
        time_welcome = SESSION_CONFIG_DEFAULTS["time_welcome"],
        time_period = SESSION_CONFIG_DEFAULTS["time_period"],
        time_intro = SESSION_CONFIG_DEFAULTS["time_intro"],
        time_next = SESSION_CONFIG_DEFAULTS["time_next"],
        time_quiz = SESSION_CONFIG_DEFAULTS["time_quiz"],
        num_ques = SESSION_CONFIG_DEFAULTS["num_ques"],
        contProb = SESSION_CONFIG_DEFAULTS["contProb"],
        die_N = SESSION_CONFIG_DEFAULTS["die_N"],
    ),
    dict(
        name='mmc_rep_TAM_Lab',
        display_name="MMC Prisoner Experiment TAM Lab",
        app_sequence=['mmc_rep_intro_off_TAM','mmc_rep_exp_off_TAM','mmc_rep_questionnaire'],
        USE_POINTS = True,
        exRate = 1250,
        real_world_currency_per_point = 1/1250,
        num_demo_participants = SESSION_CONFIG_DEFAULTS["num_demo_participants"],
        SG_lengths = SESSION_CONFIG_DEFAULTS["SG_lengths"],
        SG_totalNum = SESSION_CONFIG_DEFAULTS["SG_totalNum"],
        payoff_1 = SESSION_CONFIG_DEFAULTS["payoff_1"],
        payoff_2 = SESSION_CONFIG_DEFAULTS["payoff_2"],
        expPoints_Red = SESSION_CONFIG_DEFAULTS["expPoints_Red"],
        expPoints_Blue = SESSION_CONFIG_DEFAULTS["expPoints_Blue"],
        participation_fee = SESSION_CONFIG_DEFAULTS["participation_fee"],
        quiz_fee = SESSION_CONFIG_DEFAULTS["quiz_fee"],
        avg_earn = SESSION_CONFIG_DEFAULTS["avg_earn"],
        low_earn = SESSION_CONFIG_DEFAULTS["low_earn"],
        high_earn = SESSION_CONFIG_DEFAULTS["high_earn"],
        minExpTime = SESSION_CONFIG_DEFAULTS["minExpTime"],
        maxExpTime = SESSION_CONFIG_DEFAULTS["maxExpTime"],
        time_welcome = SESSION_CONFIG_DEFAULTS["time_welcome"],
        time_period = SESSION_CONFIG_DEFAULTS["time_period"],
        time_intro = SESSION_CONFIG_DEFAULTS["time_intro"],
        time_next = SESSION_CONFIG_DEFAULTS["time_next"],
        time_quiz = SESSION_CONFIG_DEFAULTS["time_quiz"],
        num_ques = SESSION_CONFIG_DEFAULTS["num_ques"],
        contProb = SESSION_CONFIG_DEFAULTS["contProb"],
        die_N = SESSION_CONFIG_DEFAULTS["die_N"],
    ),
    dict(
        name='mmc_rep_consent',
        display_name="MMC Prisoner Experiment Consent Form",
        app_sequence=['mmc_rep_consentform'],
        num_demo_participants = SESSION_CONFIG_DEFAULTS["num_demo_participants"],
        participation_fee = SESSION_CONFIG_DEFAULTS["participation_fee"],
        quiz_fee = SESSION_CONFIG_DEFAULTS["quiz_fee"],
        avg_earn = SESSION_CONFIG_DEFAULTS["avg_earn"],
        low_earn = SESSION_CONFIG_DEFAULTS["low_earn"],
        high_earn = SESSION_CONFIG_DEFAULTS["high_earn"],
    ),
    dict(
        name='questionaire',
        display_name="Anonymous Questionaire",
        app_sequence=['mmc_rep_questionnaire'],
        )
]


# ISO-639 code
# for example: de, fr, ja, ko, zh-hans
LANGUAGE_CODE = 'en'

# e.g. EUR, GBP, CNY, JPY
REAL_WORLD_CURRENCY_CODE = 'USD'
USE_POINTS = True

ROOMS = [
    dict(
        name='econ_exp',
        display_name='Economics Experiments',
        participant_label_file='_rooms/econ101.txt',
    ),
]

ADMIN_USERNAME = 'admin'
# for security, best to set admin password in an environment variable
ADMIN_PASSWORD = environ.get('OTREE_ADMIN_PASSWORD')

DEMO_PAGE_INTRO_HTML = """ """

SECRET_KEY = '=*tu=zp8+-a=-^#@&u^p%-+4(v$v968yc+kk@_-x_vi_qr66q^'

# if an app is included in SESSION_CONFIGS, you don't need to list it here
INSTALLED_APPS = ['otree']
